[package]
name = "q0video"
version = "0.1.0"
edition = "2021"

[dependencies]
image = { version = "0.24.9", default-features = false, features = ["png"] }

[target.'cfg(windows)'.dependencies]
windows = { version = "0.58", features = [
    "Win32_Foundation",
    "Win32_Media_MediaFoundation",
    "Win32_System_Com",
] }
