[package]
name = "q0term"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Graphical terminal for q0lang and q0shell."
[[bin]]
name = "q0term"
path = "src/main.rs"

[dependencies]
q0shell = { path = "../q0shell" }
eframe = "0.27"
egui = "0.27"
