[package]
name = "q0player"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Playback runtime for q0s and q0v media."
[[bin]]
name = "q0player"
path = "src/main.rs"

[dependencies]
q0credits = { path = "../q0credits" }
q0s-format = { path = "../q0s-format" }
q0video = { path = "../q0video" }
q0theme = { path = "../q0theme" }
eframe = "0.27"
egui = "0.27"
lyon_path = "1"
lyon_tessellation = "1"
rfd = "0.14"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
dirs = "5"
rodio = { version = "0.20", default-features = false }

[target.'cfg(windows)'.dependencies]
winreg = "0.52"

[dev-dependencies]
image = { version = "0.24.9", default-features = false, features = ["png"] }

[build-dependencies]
q0icon = { path = "../q0icon" }

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"
